server:
  port: 7070
spring:
  application:
    name: zuul
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  retryable: true
  prefix: /api
  routes:
    user-service:
      path: item/**
      service-id: user-service
  host:
    connect-timeout-millis: 4000
    socket-timeout-millis: 2000
ribbon:
  ConnectTimeout: 250
  ReadTimeout: 2000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000